version: '3'

networks:
  npm_default:
    external: true

services:
  fast_api-app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - npm_default
    ports:
      - "8900:8000"
    volumes:
      - ./database.db:/app/database.db
