"""Added photos, feeback

Revision ID: 967588a7a8c9
Revises: 70137b1b9b60
Create Date: 2024-11-06 17:15:47.785447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '967588a7a8c9'
down_revision: Union[str, None] = '70137b1b9b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('ratings', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('beer_id', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('type_feedback', sa.String(length=10), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.CheckConstraint("type_feedback IN ('beer', 'place')", name='check_type_feedback'),
    sa.ForeignKeyConstraint(['beer_id'], ['beers.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedbacks_beer_id'), 'feedbacks', ['beer_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_place_id'), 'feedbacks', ['place_id'], unique=False)
    op.create_index(op.f('ix_feedbacks_user_id'), 'feedbacks', ['user_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('feedback_id', sa.Integer(), nullable=True),
    sa.Column('beer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['beer_id'], ['beers.id'], ),
    sa.ForeignKeyConstraint(['feedback_id'], ['feedbacks.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_beer_id'), 'photos', ['beer_id'], unique=False)
    op.create_index(op.f('ix_photos_feedback_id'), 'photos', ['feedback_id'], unique=False)
    op.create_index(op.f('ix_photos_place_id'), 'photos', ['place_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_place_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_feedback_id'), table_name='photos')
    op.drop_index(op.f('ix_photos_beer_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_feedbacks_user_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_place_id'), table_name='feedbacks')
    op.drop_index(op.f('ix_feedbacks_beer_id'), table_name='feedbacks')
    op.drop_table('feedbacks')
    # ### end Alembic commands ###
