"""Removed m2m_place_beer

Revision ID: 4600797989d9
Revises: 967588a7a8c9
Create Date: 2024-11-06 22:08:56.678364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4600797989d9'
down_revision: Union[str, None] = '967588a7a8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beers_places')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beers_places',
    sa.Column('place_id', sa.INTEGER(), nullable=False),
    sa.Column('beer_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['beer_id'], ['beers.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('place_id', 'beer_id')
    )
    # ### end Alembic commands ###
