"""Added type_of_beer, m2m_place_beer, beer

Revision ID: a8e4d8eea2c1
Revises: 25d0f5a37e6a
Create Date: 2024-11-06 00:32:09.302879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8e4d8eea2c1'
down_revision: Union[str, None] = '25d0f5a37e6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_of_beers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_type_of_beers_name'), 'type_of_beers', ['name'], unique=False)
    op.create_table('beers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('brand', sa.String(length=45), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('photo', sa.String(length=100), nullable=True),
    sa.Column('alc_degree', sa.DECIMAL(precision=2, scale=2), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['type_of_beers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beers_places',
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.Column('beer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['beer_id'], ['beers.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('place_id', 'beer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beers_places')
    op.drop_table('beers')
    op.drop_index(op.f('ix_type_of_beers_name'), table_name='type_of_beers')
    op.drop_table('type_of_beers')
    # ### end Alembic commands ###
